### ISSUE TITLE
Some clarifications needed

### ISSUE THREAD

**Issue by nathany** [convox/site#77]
I have just read through all the documentation, but not yet paid the $ to install a Rack. A few things aren't clear in my mind, which may be the case to other new users.

It says it's safe to delete the IAM convox user. Does uninstalling convox still work if that user is gone? Btw, [Using the CLI Installer](http://convox.github.io/docs/using-the-cli-installer/) mentions the AWS credentials but doesn't elaborate on how to do that or people very new to AWS, likely using `aws login` (brew install awscli).

It's not entirely clear if [run and exec](http://convox.github.io/docs/one-off-runs/) run on the Rack or against a local Docker development environment. I'm presuming the former, but it could be stated more plainly.

[Developing Locally](http://convox.github.io/docs/developing-locally/) uses Docker images convox/postgres and convox/redis for local development. There is also documentation on RDS and ElastiCache services. It's not clear if it's possible to setup a development environment that uses both in combination, as I presume Convox will attempt to deploy those containers as well?

**Comment by soulshake** [comment]
Hi @nathany, thanks for the feedback and sorry about the delayed reply.

`It's not entirely clear if run and exec run on the Rack or against a local Docker development environment. I'm presuming the former, but it could be stated more plainly.`

I've just submitted a [PR](https://github.com/convox/site/pull/330) to clarify the `run` and `exec` commands, so that documentation should be much clearer soon.

Regarding the rest, I think this has gotten better since this issue was created. If not, we can take a look.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [convox/site issue triage](https://trello.com/c/Btj649kR/1081-convox-site-issue-triage)
